### GET ALL
GET http://localhost:3000/api/servicios

### POST 
# @name createServicio
POST http://localhost:3000/api/servicios
Content-Type: application/json

{
    "descripcion": "Servicio de limpieza",
    "nombre": "Limpieza",
    "tipoServicio": 1
}

### ID 
@id = {{createServicio.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/servicios/{{id}}

### PUT
PUT http://localhost:3000/api/servicios/{{id}}
Content-Type: application/json

{
    "descripcion": "Servicio de jardineria",
    "nombre": "Jardineria",
    "tipoServicio": 1
}


### DELETE
DELETE http://localhost:3000/api/servicios/{{id}}
