### GET ALL
GET http://localhost:3000/api/tiposServicios

### POST 
# @name createTipoServicio
POST http://localhost:3000/api/tiposServicios
Content-Type: application/json

{
    "descripcion": "Limpieza general"
}

### ID 
@id = {{createTipoServicio.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/tiposServicios/{{id}}

### PUT
PUT http://localhost:3000/api/tiposServicios/{{id}}
Content-Type: application/json

{
    "descripcion": "Jardineria"
}


### DELETE
DELETE http://localhost:3000/api/tiposServicios/{{id}}
