###Obtener todos los tipos de servicios
GET http://localhost:3000/api/tiposServicios

###Obtener un tipo de servicio específico
GET http://localhost:3000/api/tiposServicios/7f726685-65e7-4118-832a-1f4701b1ef5c


###Crear un nuevo tipo de servicio
POST http://localhost:3000/api/tiposServicios
Content-Type: application/json

{
  "nombre": "Cerrajería",
  "descripcion": "Servicio de cerrajería general"
}

###Modificar un tipo de servicio existente (PUT)
PUT http://localhost:3000/api/tiposServicios/7f726685-65e7-4118-832a-1f4701b1ef5c
Content-Type: application/json

{
  "nombre": "Plomería Avanzada",
  "descripcion": "Servicio de plomería avanzado"
}

###Eliminar un tipo de servicio
DELETE http://localhost:3000/api/tiposServicios/62dc1925-a76b-4a87-952e-ea9ae5457961