### GET ALL
GET http://localhost:3000/api/publicaciones

### POST 
# @name createPublicacion
POST http://localhost:3000/api/publicaciones
Content-Type: application/json

{
    "descripcion": "Servicios de reparacion y mantenimiento en el hogar",
    "estado": "Aprobada",
    "fechaPublicacion": "2024-08-30",
    "titulo": "Servicios de Reparacion y Mantenimiento",
    "precio": 30.000,
    "usuario_id": 1,
    "servicio_id": 100
}

### ID 
@id = {{createPublicacion.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/publicaciones/{{id}}

### PUT
PUT http://localhost:3000/api/publicaciones/{{id}}
Content-Type: application/json

{
    "descripcion": "Plomeria, electricidad y mantenimiento en general",
    "estado": "Aprobada",
    "fechaPublicacion": "2024-06-16",
    "titulo": "Servicios de Mantenimiento",
    "precio": 32.500,
    "usuario_id": 1,
    "servicio_id": 101    
}

### POST CIUDAD TO DELETE
# @name createPublicacionToDelete
POST http://localhost:3000/api/publicaciones
Content-Type: application/json

{
    "descripcion": "Se realiza todo tipo de limpieza",
    "estado": "Pendiente",
    "fechaPublicacion": "2024-06-18",
    "titulo": "Servicios de Limpieza",
    "precio": 10.000,
    "usuario_id": 1,
    "servicio_id": 103
}


### DELETE
@idToDelete = {{createPublicacionToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/publicaciones/{{id}}
