### GET ALL
GET http://localhost:3000/api/publicaciones

### POST 
# @name createPublicacion
POST http://localhost:3000/api/publicaciones
Content-Type: application/json

{
    "descripcion": "Se realizan todo tipo de reparaciones",
    "estado": "Aprobada",
    "cliente": 1,
    "servicio": 1  
}

### ID 
@id = {{createPublicacion.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/publicaciones/{{id}}

### PUT
PUT http://localhost:3000/api/publicaciones/{{id}}
Content-Type: application/json

{
    "descripcion": "Se realizan todo tipo de reparaciones y mantenimiento",
    "estado": "Rechazada",
    "cliente": 1,
    "servicio": 1
}

### POST CIUDAD TO DELETE
# @name createPublicacionToDelete
POST http://localhost:3000/api/publicaciones
Content-Type: application/json

{
    "descripcion": "Se realiza todo tipo de limpieza",
    "estado": "Pendiente",
    "cliente": 1,
    "servicio": 1
}


### DELETE
@idToDelete = {{createPublicacionToDelete.response.body.data.id}}
DELETE http://localhost:3000/api/publicaciones/{{id}}
